### PR TITLE
Some updates to blastn data manager.

### PR DESCRIPTION
**Pull request by davebx**

### CODE REVIEW

**Comment by bimbam23** [comment]
Hi Dave, it looks like the merged commit worked but all changes did not happen? Do you know what I have to do so get the changed files?

**Comment by davebx** [comment]
I had a look, and it looks like git forgot to remove `data_manager_blastn_for_fasta_and_dbs` or whatever it was called. I'm working on fixing the rest of my errors now, might have another pull request up within the next 3 hours, might not.

**Comment by bimbam23** [comment]
Perfect 👌 thx

**Comment by bimbam23** [comment]
For me it looks like the merged file did not merge proper.

**Pull request merged**
